# Generated by Django 4.2.1 on 2023-06-01 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField()),
                ('product_code', models.CharField(max_length=255, unique=True)),
                ('product_batch', models.IntegerField()),
                ('product_description', models.CharField(max_length=255)),
                ('product_production_date', models.DateTimeField()),
                ('product_expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('store_cnpj', models.CharField(unique=True)),
                ('store_name', models.CharField(max_length=255)),
                ('store_trading_name', models.CharField(max_length=255)),
                ('store_address', models.CharField(max_length=255)),
                ('store_email', models.EmailField(max_length=255)),
                ('store_phone_number', models.CharField(max_length=255)),
                ('store_manager_cpf', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('employee_cpf', models.CharField()),
                ('store_manager_cpf', models.CharField()),
                ('order_quantity', models.IntegerField()),
                ('order_motive', models.IntegerField()),
                ('order_confirmation_status', models.IntegerField()),
                ('order_creation_date', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.product')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.store')),
            ],
        ),
    ]
